### ISSUE TITLE
Is rendering documentation available?

### ISSUE THREAD

**Issue by tylerssn** [google/node-gles#13]
When it comes to rendering, should I be referring to WebGL, OpenGL or other docs?

**Comment by nkreeger** [comment]
WebGL is the currently exposed API. I’ll update the docs shortly to show how to create a context.

**Comment by nkreeger** [comment]
@tylerssn Sorry for the lag - I updated the main README to show how to create a WebGL context:

https://github.com/google/node-gles#creating-a-webgl-context

API is the same as WebGL in the browser on the `gl` object once you create it.
